In [1]:
%cd "F:\Google Drive\JupyterNotebooks\PMega"

F:\Google Drive\JupyterNotebooks\PMega


### The case for Numpy
Pictures are just spreadsheets of numbers
You can store them in lists, but this is really slow and takes up a lot of memory.
Enter Numpy!

In [6]:
import numpy
n = numpy.arange(30)

In [7]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
# note that this is NOT a list
type(n)

numpy.ndarray

In [8]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]


### Making a 2D array

In [9]:
n.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

### Making a 3d array

In [10]:
n.reshape(3,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

###  Numpy arrays out of lists

In [12]:
m = numpy.asarray([[1,2,3],[3,4,5]])

In [13]:
m

array([[1, 2, 3],
       [3, 4, 5]])

### Creating a numpy array from an image file

In [17]:
import cv2
import os
os.listdir()

['06.55 Reading Files.ipynb',
 '6.60 Exercise.ipynb',
 '9.95 Importing into Pandas.ipynb',
 '9.96 Data Slicing.ipynb',
 'app1.py',
 'exercise',
 'exercise.txt',
 'fruits.txt',
 'General Notes.ipynb',
 'Numpy 01 - Working with arrays.ipynb',
 'smallgray.png',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx']

In [18]:
im_g = cv2.imread("smallgray.png",0) #imread is the image reading thing. 0 = greyscale, 1 = bgr
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [20]:
im_c = cv2.imread("smallgray.png",1)
im_c

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

### What about making images out of numpy arrays?

In [21]:
cv2.imwrite("newsmallgray.png",im_g)

True

In [22]:
os.listdir()

['06.55 Reading Files.ipynb',
 '6.60 Exercise.ipynb',
 '9.95 Importing into Pandas.ipynb',
 '9.96 Data Slicing.ipynb',
 'app1.py',
 'exercise',
 'exercise.txt',
 'fruits.txt',
 'General Notes.ipynb',
 'newsmallgray.png',
 'Numpy 01 - Working with arrays.ipynb',
 'smallgray.png',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx']

### Slicing etc

In [23]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

#### Slicing in multiple dimensions

In [25]:
im_g[0:2,2:4] #rows, then columns

array([[104, 121],
       [255, 255]], dtype=uint8)

In [26]:
im_g.shape

(3, 5)

In [27]:
im_g[:,2:3]

array([[104],
       [255],
       [255]], dtype=uint8)

### Iterating

In [28]:
for i in im_g:
    print(i) #note that i = rows

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [29]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [31]:
for i in im_g.flat:
    print(i)        # this gives us access to the values of our thing one by one

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


### Stacking and splitting

In [34]:
ims = numpy.hstack((im_g,im_g)) #use a tuple of numpy arrays
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [35]:
ims_v = numpy.vstack((im_g,im_g))
ims_v

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

Note that the arrays need to have the same dimensions

In [36]:
lst = numpy.hsplit(ims,5)

In [37]:
lst

[array([[187, 158],
        [198, 125],
        [209, 134]], dtype=uint8), array([[104, 121],
        [255, 255],
        [255,  97]], dtype=uint8), array([[143, 187],
        [147, 198],
        [182, 209]], dtype=uint8), array([[158, 104],
        [125, 255],
        [134, 255]], dtype=uint8), array([[121, 143],
        [255, 147],
        [ 97, 182]], dtype=uint8)]

In [39]:
lst_2 = numpy.vsplit(ims_v,3)

In [40]:
lst_2

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]